import img from './img/news.jpg';

export const NewsList = [
  {
    name: "Notícia 1",
    category: "Lançamentos",
    text: "Lorem ipsum dolor adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 2",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 3",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 4",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 5",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 6",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 7",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 8",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
  {
    name: "Notícia 9",
    category: "Lançamentos",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    img: img,
    url: "#",
    readmore: 'Leia mais',
  },
];
